### ISSUE TITLE
"from soundsig.sound import BioSound" fails because "ImportError: cannot import name 'RandomizedPCA' from 'sklearn.decomposition'" with sklearn 0.20.3

### ISSUE THREAD

**Issue by VincentRouvreau** [theunissenlab/BioSoundTutorial#1]
On Windows 10 x64, with Python 3.7 (conda or classic installation), import soundsig works but "from soundsig.sound import BioSound" fails.

Here is the complete log :
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> from soundsig.sound import BioSound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\lib\site-packages\soundsig\sound.py", line 29, in <module>
    from soundsig.signal import lowpass_filter, gaussian_window, correlation_function
  File "C:\Miniconda3\lib\site-packages\soundsig\signal.py", line 11, in <module>
    from sklearn.decomposition import PCA,RandomizedPCA
ImportError: cannot import name 'RandomizedPCA' from 'sklearn.decomposition' (C:\Miniconda3\lib\site-packages\sklearn\decomposition\__init__.py)

In Scikit-learn, RandomizedPCA is deprecated since version 0.20.2, cf. https://stackoverflow.com/questions/54494785/sklearn-0-20-2-import-error-with-randomizedpca

**Comment by sridharajanardhan** [comment]
from sklearn.decomposition import PCA
# Create a Randomized PCA model that takes two components
randomized_pca = PCA(n_components=2,svd_solver='randomized')
